name: Discovery API

on:
  pull_request:
    paths:
      - 'apps/api/**'
  push:
    branches:
      - main
      - dev
    paths:
      - 'apps/api/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: '3.12'

      - name: Cache Poetry packages
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('apps/api/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install dependencies
        working-directory: apps/api
        run: poetry install
      - name: Run lint
        working-directory: apps/api
        run: poetry run ruff check discovery/ tests/
      - name: Run tests
        working-directory: apps/api
        run: poetry run pytest --disable-warnings tests/ --cov --junitxml=junit.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4.0.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
       