name: Discovery API

on:
  pull_request:
    paths:
      - 'apps/api/**'
  push:
    branches:
      - main
      - dev
    paths:
      - 'apps/api/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.12'

      - name: Cache Poetry packages
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('apps/api/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install dependencies
        working-directory: apps/api
        run: poetry install
      - name: Run lint
        working-directory: apps/api
        run: poetry run ruff check discovery/ tests/
      - name: Run tests
        working-directory: apps/api
        run: poetry run pytest --disable-warnings tests/ --cov --junitxml=junit.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
       