name: Generate OpenAPI Docs and Create PR

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**.py'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  generate-openapi:
    name: generate OpenAPI
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.12'

      - name: Cache Poetry packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('apps/api/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install dependencies
        working-directory: apps/api
        run: |
          poetry config virtualenvs.create false 
          poetry install --no-dev --no-interaction --no-ansi

      - name: Generate OpenAPI JSON
        working-directory: apps/api
        run: |
          poetry run python -c "
          import json;
          from fastapi.openapi.utils import get_openapi;
          from discovery.app import app;
          with open('${{runner.temp}}/openapi.json', 'w') as f:
              json.dump(
                  get_openapi(
                      title=app.title,
                      version=app.version,
                      openapi_version=app.openapi_version,
                      description=app.description,
                      routes=app.routes,
                  ),
                  f,
              )"
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: main
      - name: Move OpenAPI JSON to PR branch
        run: |
          cp ${{runner.temp}}/openapi.json ./docs/src/openapi.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c #v6.10
        with:
          commit-message: 'docs(openapi): update OpenAPI documentation'
          branch: 'update-openapi-docs'
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch-suffix: 'short-commit-hash'
          title: 'docs(openapi): update OpenAPI documentation'
          body: |
            # docs(openapi): update OpenAPI documentation

            ## Description

            This pull request updates the OpenAPI documentation by generating a new `openapi.json` file. This update ensures that the documentation is in sync with the latest API changes.

            - Auto-generated by [create-pull-request][https://github.com/peter-evans/create-pull-request]
          labels: |
            automated pr
