name: Generate OpenAPI Docs and Create PR

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**.py'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  generate-openapi:
    name: generate OpenAPI
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'

      - name: Cache Poetry packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('apps/api/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install dependencies
        working-directory: apps/api
        run: |
          poetry config virtualenvs.create false 
          poetry install --no-dev --no-interaction --no-ansi

      - name: Generate OpenAPI JSON
        working-directory: apps/api
        run: |
          poetry run python -c "
          import json;
          from fastapi.openapi.utils import get_openapi;
          from discovery.app import app;
          with open('${{runner.temp}}/openapi.json', 'w') as f:
              json.dump(
                  get_openapi(
                      title=app.title,
                      version=app.version,
                      openapi_version=app.openapi_version,
                      description=app.description,
                      routes=app.routes,
                  ),
                  f,
              )"
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
      - name: Move OpenAPI JSON to PR branch
        run: |
          cp ${{runner.temp}}/openapi.json ./docs/src/openapi.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: 'docs(openapi): update OpenAPI documentation'
          branch: 'update-openapi-docs'
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch-suffix: 'short-commit-hash'
          title: 'docs(openapi): update OpenAPI documentation'
          body: |
            # docs(openapi): update OpenAPI documentation

            ## Description

            This pull request updates the OpenAPI documentation by generating a new `openapi.json` file. This update ensures that the documentation is in sync with the latest API changes.

            - Auto-generated by [create-pull-request][https://github.com/peter-evans/create-pull-request]
          labels: |
            automated pr
